# Generated by Django 4.2.3 on 2024-04-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_alter_usermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequestmodel',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
